name: Build Windows DLL

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
      
    - name: Setup CMake
      uses: cmake-js/cmake-js@main
      with:
        cmake-version: '3.21.0'
    
    - name: Create build directory
      run: mkdir build
      
    - name: Configure CMake
      run: |
        cd build
        cmake .. -G "Visual Studio 17 2022" -A x64
        
    - name: Build with CMake
      run: |
        cd build
        cmake --build . --config Release
        
    - name: Direct compilation (backup method)
      run: |
        cl.exe /LD /Fe:WinosTestPlugin_direct.dll WinosTestPlugin.cpp user32.lib
      shell: cmd
      
    - name: List generated files
      run: |
        echo "=== CMake build output ==="
        dir build\Release\
        echo "=== Direct compilation output ==="
        dir *.dll
      shell: cmd
      
    - name: Upload DLL artifacts
      uses: actions/upload-artifact@v4
      with:
        name: WinosTestPlugin-dll
        path: |
          build/Release/*.dll
          *.dll
        retention-days: 30
        
    - name: Create Release (if tagged)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          build/Release/*.dll
          *.dll
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}